### ISSUE TITLE
No message for fertilized crops

### ISSUE THREAD

**Issue by 4x4cheesecake** [dmcrider/LastDayToPlant#16]
Despite setting the config for speedgro to "true", no ingame message will be shown to remind you for the last day to plant a fertilized crop. I've investigated the issue already and here is my result:

The reason seems to be a wrong calculation here: https://github.com/dmcrider/LastDayToPlant/blob/main/ModEntry.cs#L68

For the regular crops without fertilizer, you calculate "daysLeft" by adding the current day to the time it takes for the crop to mature and then check if this is equal the number of days in the month (const = 28).

For example: Cauliflower

DaysInAMonth = 28
DaysToMature = 13
day = 15

so you code calculates: 

> var daysLeft = crop.DaysToMature + day;

to 

> var daysLeft = 13 + 15;

and the if-statement becomes true (assuming the config is set to true):

> if (daysLeft == DaysInAMonth && MyConfig.ShowBaseCrops)

For fertilized crops, your code does something similar but not quite the same:

You calculate "boostedDaysLeft" by subtracting the speedbonus of fertilizer and the agricultist skill from the grow time and then check if this is equal to the days in a month:

> double boostedDaysLeft = crop.DaysToMature;
[...]
> boostedDaysLeft -= crop.DaysToMature * Fertilizer.SpeedGro;
> if(boostedDaysLeft == DaysInAMonth)
> [...]

This will never be true for two reasons:
1) the days to mature are always less then the days in a month
2) you compare a floatpoint value to an integer, which will almost never match

Let's pick up the cauliflower example again and calculate the values for regular speedgrow without agricultist skill:

DaysInAMonth = 28
DaysToMature = 13
Fertilizer.SpeedGro = 0.1

so you code calculates:

>  double boostedDaysLeft = crop.DaysToMature;

to 

>  double boostedDaysLeft = 13;

and 

> boostedDaysLeft -= crop.DaysToMature * Fertilizer.SpeedGro;

to 

> boostedDaysLeft -= 13 * 0.1;

which results in 

> boostedDaysLeft = 11.7

The following if-statement can never be true:

> if(boostedDaysLeft == DaysInAMonth)

because it compares the fertilized grow time of the crop to the days in a month:

> if(11.7 == 28)

You can fix this by adding the current day to "boostedDaysLeft", like you've done for the unfertilized crops and then casting the double into an integer. 
I rewrote this part already on a local copy of your code and it works perfectly fine now (I went a step further and added a new method though). If you're interest, I can share my changes with you or even create a pull request :)

**Comment by dmcrider** [comment]
That's awesome, thank you! Please create a pull request and I will review it and merge it. Unfortunately my full-time job has taken over my life these past few weeks so I haven't been able to work on this as much as I would like.

**Comment by dmcrider** [comment]
Fixed in the linked pull request

**Comment by 4x4cheesecake** [comment]
Much appreciated, thank you :)
